force-app/main/default/objects/InstallationContract__c/InstallationContract__c.object-meta.xml
<CustomObject>
    <label>Contrato de Instalación</label>
    <nameField>
        <label>Contrato de Instalación Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Instalacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InstallationContract__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Pendientes de revisión</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/rivas/classes/MonthlyContractReviewBatch.cls
global with sharing class MonthlyContractReviewBatch implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Date cutoff = Date.today().addDays(-30);
        return Database.getQueryLocator([SELECT Id, Estado__c FROM InstallationContract__c WHERE Estado__c = 'En proceso' AND LastModifiedDate <= :DateTime.newInstance(cutoff, Time.newInstance(0,0,0,0))]);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<InstallationContract__c> toUpdate = new List<InstallationContract__c>();

        for (InstallationContract__c c : (List<InstallationContract__c>) scope) {
            c.Estado__c = 'Pendientes de revisión';
            toUpdate.add(c);
        }
        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }
    
    global void finish(Database.BatchableContext bc) {
    }
}
/*
MonthlyContractReviewBatch batch = new MonthlyContractReviewBatch();
Database.executeBatch(batch, 200);
*/